One click unsubscribe url
alphagov/notifications-tech-docs pull request #228
Opened 2024-05-16 15:19 UTC by BlessedDev

This PR updates all our API client documents and the generic API document to detail the addition of the `one_click_unsubscribe_url` parameter.

2024-05-17 10:17 UTC, quis requested changes
Only some of the clients have the _Response_ section of `get_notification` updated to include `one_click_unsubscribe_url`. We should be consistent about this across the clients

2024-05-17 10:17 UTC, quis commented on source/documentation/_api_docs.md
> +The one-click unsubscribe URL must respond to an empty POST request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```suggestion
The one-click unsubscribe URL must respond to an empty `POST` request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_java.md
> +The one-click unsubscribe URL must respond to an empty POST request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```suggestion
The one-click unsubscribe URL must respond to an empty `POST` request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_net.md
> +The one-click unsubscribe URL must respond to an empty POST request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```suggestion
The one-click unsubscribe URL must respond to an empty `POST` request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_node.md
> +The one-click unsubscribe URL must respond to an empty POST request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```suggestion
The one-click unsubscribe URL must respond to an empty `POST` request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_php.md
> +The one-click unsubscribe URL must respond to an empty POST request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```suggestion
The one-click unsubscribe URL must respond to an empty `POST` request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_python.md
> +The one-click unsubscribe URL must respond to an empty POST request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```suggestion
The one-click unsubscribe URL must respond to an empty `POST` request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_ruby.md
> +The one-click unsubscribe URL must respond to an empty POST request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```suggestion
The one-click unsubscribe URL must respond to an empty `POST` request by unsubscribing the user from your emails. You can include query parameters to help you identify the user.
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_php.md
> +
I don’t think we need this – it duplicates the second paragraph
```suggestion
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_php.md
> +        'https://example.com/unsubscribe.html?opaque=123456789'
I don’t think we should include this in the default example – the more common use case will be to not have an unsubscribe URL
```suggestion
        '862bfaaf-9f89-43dd-aafa-2868ce2926a9'
```

2024-05-17 10:17 UTC, quis commented on source/documentation/_api_docs.md
> +
Our pattern for optional arguments seems to be explaining why they are optional in the final paragraph – this is duplicative
```suggestion
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_java.md
> +
Our pattern for optional arguments seems to be explaining why they are optional in the final paragraph – this is duplicative
```suggestion
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_net.md
> +
Our pattern for optional arguments seems to be explaining why they are optional in the final paragraph – this is duplicative
```suggestion
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_node.md
> +
Our pattern for optional arguments seems to be explaining why they are optional in the final paragraph – this is duplicative
```suggestion
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_php.md
> +
Our pattern for optional arguments seems to be explaining why they are optional in the final paragraph – this is duplicative
```suggestion
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_python.md
> +
Our pattern for optional arguments seems to be explaining why they are optional in the final paragraph – this is duplicative
```suggestion
```

2024-05-17 10:17 UTC, quis commented on source/documentation/client_docs/_ruby.md
> +
Our pattern for optional arguments seems to be explaining why they are optional in the final paragraph – this is duplicative
```suggestion
```

2024-05-20 10:23 UTC, BlessedDev commented on source/documentation/client_docs/_php.md
> +        'https://example.com/unsubscribe.html?opaque=123456789'
In this case I followed the pattern where `reference` was added in the example although it is an optional argument. Also it is a good way to draw attention to the new feature.

2024-05-20 10:51 UTC, leohemsted approved these changes

2024-05-20 11:55 UTC, merged