Add returned letters callback
alphagov/notifications-tech-docs pull request #263
Opened 2024-11-29 12:33 UTC by BlessedDev

This PR is a draft documentation of the proposed API callback for returned letters as described in this [card](https://trello.com/c/MqwEyn03/155-write-draft-documentation-for-api-callbacks-for-returned-letters)

2024-11-29 17:22 UTC, CrystalPea reviewed
Looks good to me - well done both of you 🙌🏼 

I will chat up the users who requested info about returned letters via API, and see what they say 👍🏼

2025-02-19 10:40 UTC, quis requested changes

2025-02-19 10:40 UTC, quis commented on source/documentation/_callbacks.md
> +When a letter you sent is returned, Notify will send details of the returned letter to your callback url.
```suggestion
When a letter you sent is returned, Notify will send details of the returned letter to your callback URL.
```

2025-02-19 10:40 UTC, quis commented on source/documentation/_callbacks.md
> +| #`spreadsheet_row_number`| The row in the spreadsheet  | `1` |
This field will never be `1`. Should we also say that?
```suggestion
| #`spreadsheet_row_number`| The row in the spreadsheet  | `2` |
```

2025-02-19 10:40 UTC, quis commented on source/documentation/_callbacks.md
> +| #`reference` | The reference sent by the service | `12345678` or null |
We don’t say _or null_ for other fields which are nullable (for example `sent_by`). Maybe we should say _optional_ for these fields instead? We should avoid `null` specifically because only exists in some languages, for example Python has `None`, Ruby has `nil`.
```suggestion
| #`reference` | The reference sent by the service | `12345678` |
```

2025-02-19 10:40 UTC, quis commented on source/documentation/_callbacks.md
> +| #`notification_id` | Notify’s id for the returned letter | UUID |
We capitalise this elsewhere in the docs
```suggestion
| #`notification_id` | Notify’s ID for the returned letter | UUID |
```

2025-02-19 10:40 UTC, quis commented on source/documentation/_callbacks.md
> +The callback message is formatted in JSON. All of the values are strings. The key, description and format of the callback message arguments will be:
```suggestion
The callback message is formatted in JSON. The key, description and format of the callback message arguments will be:
```

2025-02-19 11:14 UTC, quis commented on source/documentation/_callbacks.md
> +| #`reference` | The reference sent by the service | `12345678` or null |
For consistency with the documentation of other callbacks I’m going to keep this the same and add null to the other fields

2025-02-19 11:15 UTC, quis commented on source/documentation/_callbacks.md
> +| #`sent_by` | The email address of the service member who sent the letter | `hello@gov.uk`|
```suggestion
| #`sent_by` | The email address of the service member who sent the letter | `hello@gov.uk` or null |
```

2025-02-19 11:15 UTC, quis commented on source/documentation/_callbacks.md
> +| #`spreadsheet_file_name`| The name of the uploaded spreadsheet | `contact_list.csv` |
```suggestion
| #`spreadsheet_file_name`| The name of the uploaded spreadsheet | `contact_list.csv`  or null |
```

2025-02-19 11:15 UTC, quis commented on source/documentation/_callbacks.md
> +| #`upload_letter_file_name`| The name of the uploaded letter | `uploaded_letter.pdf` |
```suggestion
| #`upload_letter_file_name`| The name of the uploaded letter | `uploaded_letter.pdf`  or null |
```

2025-02-19 11:16 UTC, quis commented on source/documentation/_callbacks.md
> +| #`spreadsheet_row_number`| The row in the spreadsheet  | `1` |
```suggestion
| #`spreadsheet_row_number`| The row in the spreadsheet  | `2` or null |
```

2025-02-25 16:22 UTC, merged